### ISSUE TITLE
Update API level to 6.7

### ISSUE THREAD

**Issue by dbmeneses** [SonarQubeCommunity/sonar-scm-mercurial#5]
The SonarQube API that was deprecated before version 5.6 will dropped soon.
It can be tested with SonarQube artifact 7.0.0.34895 (or newer one from the branch 'feature/dm/sq56').

More information: https://jira.sonarsource.com/browse/SONAR-10138

**Comment by simonbrandhof** [comment]
This change is required for the support of SonarQube 7.2+ and the end of support of compatibility mode: https://jira.sonarsource.com/browse/SONAR-10541

**Comment by henryju** [comment]
We should also implement new methods on the SCMProvider.

**Comment by simonbrandhof** [comment]
@henryju FYI my PR to upgrade to API 6.7 has been merged, without implementing the new methods.

**Comment by simonbrandhof** [comment]
@dbmeneses @henryju what's the effort to implement the new methods ? I wonder if version 1.2 should be released without this feature.

**Comment by dbmeneses** [comment]
Implementing the new methods takes some time as it requires investigating how to detect changes within a branch. These methods are optional and I think it can be extracted to a different issue so that we release 1.2.
